### ISSUE TITLE
[BUG] LocalPen not loading in Safari

### ISSUE THREAD

**Issue by iocouto** [hatemhosny/localpen#132]
Currently, visiting "https://localpen.io" with the latest version of Safari, both on Big Sur as well as on the latest iOS and iPadOS, yields a never-ending loading screen:

<img width="421" alt="Screen Shot 2021-08-12 at 4 47 58 pm" src="https://user-images.githubusercontent.com/75245963/129150806-40d591f0-c768-4953-b1b7-28d1d30c39e7.png">

Calling up the console on Safari MacOS, we see only 1 error - not sure whether it's helpful or not:

<img width="803" alt="Screen Shot 2021-08-12 at 4 46 52 pm" src="https://user-images.githubusercontent.com/75245963/129150887-86383da7-d209-4be3-b3ec-5ebb446c0f75.png">

Visiting the site with Firefox or Chrome loads the LocalPen interface as expected - problem only appears on Safari, on all platforms.

**Comment by hatemhosny** [comment]
Hi @iocouto 

Thank you for reporting.

This has already been fixed.
You can test it on the development build:
https://dev.localpen.io/

The fix will be published (with lots of other features and fixes) on the next release. 
LocalPen is being actively developed. The next release will be published once it is relatively stable.

Please let me know how you find it.

Thank you 😊

**Comment by iocouto** [comment]
Can confirm: https://dev.localmente.io loading as expected on all platforms. 👍🎉
